import 'regenerator-runtime';
import { createTheme } from "@mui/material/styles";


/**
 * Post a users signup information to db, allowing for login with username/password
 * @async
 * @function postSignup
 * @param {string} user - the user's unique created username
 * @param {string} pass - the user's created password
 * @param {string} arn - the inputted stack's arn
 * @param {string} region - the user's inputted account region
 * @param {number} EXTERNAL_ID - a unique number generated by uuid
 * @returns {undefined}
 */
export const postSignup = async (user, pass, arn, region, EXTERNAL_ID) => {
  try {
    console.log(EXTERNAL_ID);
    const data = await fetch('/api/user/signup', {
      method: 'POST',
      body: JSON.stringify({
        username: user,
        password: pass,
        arn: arn,
        region: region,
        externalId: EXTERNAL_ID
      }),
      headers: {
        'Content-Type': 'application/json'
      }
    });   
  } catch (err) {
    console.log(err);
  }
}

export const postLogout = async (setLogin) => {
  try {
    const data = await fetch('/api/user/logout', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      }
    })
    setLogin(false);
  } catch (err) {
    console.log(err);
  }
}

export const themeLight = createTheme({
  palette: {
    type: 'light',
    primary: {
      main: '#3f51b5',
    },
    secondary: {
      main: '#9ccc65',
    },
    info: {
      main: '#2196f3',
    },
  }
});

export const themeDark = createTheme({
  palette: {
    type: 'dark',
    // mode: 'dark',
    primary: {
      main: '#8bc34a',
    },
    secondary: {
      main: '#124116',
    },
    info: {
      main: '#2196f3',
    },
  }
});